name: Github Runner CICD

run-name: Deploy on Github Runner

on: [push]
jobs:
  deploy-github-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' 

      - name: Install Dependencies
        run: |
          npm install
          npm install pm2

      - name: Deploy
        run: pm2 start server.js